some improvements during usage in a project
Azure-Samples/ms-identity-b2c-java-servlet-webapp-authentication pull request #2
Opened 2021-02-21 16:17 UTC by bkiselka

1) pom.xml use msal4j > 1.8.0 because IAccount is serializable then, see https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/changelog.txt and https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/292

2) AuthHelper.java and authentication.properties: add a configuration property app.prompt: the value might be login, select_account (was/is the default), consent, admin_consent or not set/empty (none), see https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-prompt-behavior

3) AuthHelper.java: remove one unnecessary variable initialization (line 35/36) and check (line 228/238) causing a warning

4) AuthHelper.java: improve exception, if state is null or doesn't match or TTL expired
(this will happen, if different session e.g. caused by different domains used as URL (used in the browser), app.redirectUri and app.homePage do not match!)

5) index.jsp: enable call / (e.g. http://localhost:8080/ms-identity-b2c-java-servlet-webapp-authentication/ - no need to call /index )

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2021-03-06 08:59 UTC, idg-sam requested changes
Great stuff. I think the sample should demonstrate the prompt options.

I made some comments and suggestions. If you want to update and commit based on the suggestions I'll merge them.

2021-03-06 08:59 UTC, idg-sam commented on pom.xml
> +            <version>1.8.1</version>
```suggestion
            <version>1.9.1</version>
```

2021-03-06 08:59 UTC, idg-sam commented on src/main/webapp/index.jsp
> +%>
Already resolved by adding extra route matchers to the servlet that match empty ("/"), /sign_in_status, and /index

2021-03-06 08:59 UTC, idg-sam commented on src/main/resources/authentication.properties
> +app.prompt=select_account
Great stuff. Nice demonstration of the available options.
Is it more correct for us to call this `aad.prompt`, since we are changing the behaviour of the AAD sign in page?

2021-03-06 08:59 UTC, idg-sam commented on src/main/java/com/microsoft/azuresamples/authenticationb2c/AuthHelper.java
>                      .responseMode(ResponseMode.QUERY).prompt(Prompt.SELECT_ACCOUNT).state(state).nonce(nonce).build();
```suggestion
```
Maybe these lines are no longer necessary if we make the app require `aad.prompt` config.

2021-03-06 08:59 UTC, idg-sam commented on src/main/java/com/microsoft/azuresamples/authenticationb2c/AuthHelper.java
> +            if (!PROMPT.trim().equals("")) {
```suggestion
        } else if (!PROMPT.trim().equals("")) {
```
Maybe we can just delete the null check and require the `aad.prompt` config. the config loader causes the program to exit if there is a null param anyhow.

2021-03-24 11:47 UTC, bkiselka commented on src/main/webapp/index.jsp
> +%>
Hm, could be but I did not succeed in finding/adding these extra route matchers in the servlet. 
What I did: I tried to change line 10 of HomePageServlet.java from
```@WebServlet(name = "HomePageServlet", urlPatterns = "/index") ```
to 
```@WebServlet(name = "HomePageServlet", urlPatterns = {"/index", "/"}) ```
but still calling http://localhost:8080/ms-identity-b2c-java-servlet-webapp-authentication/ on a tomcat brought a NullPointerException because the bodyContent is null and thus cannot be included in index.jsp
It works, if I call it with http://localhost:8080/ms-identity-b2c-java-servlet-webapp-authentication/index tought!

2021-04-24 00:38 UTC, closed without merging

2021-04-24 00:40 UTC, idg-sam commented
https://github.com/Azure-Samples/ms-identity-java-servlet-webapp-authentication/issues/10